name: BetSweet
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  http: ^1.1.0
  flutter_bloc: ^8.1.3
  fancy_password_field: ^2.0.0
  country_code_picker: ^3.0.0
  carousel_slider: ^4.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/calculatorPink.svg
    - assets/icons/alertDark.svg
    - assets/icons/arrowMid.svg
    - assets/icons/ballDark.svg
    - assets/icons/ballLight.svg
    - assets/icons/ballMid.svg
    - assets/icons/bell.svg
    - assets/icons/calculatorDark.svg
    - assets/icons/calculatorMid.svg
    - assets/icons/calculatorPink.svg
    - assets/icons/cashLight.svg
    - assets/icons/chartDark.svg
    - assets/icons/chartMid.svg
    - assets/icons/chartPink.svg
    - assets/icons/crossBlue.svg
    - assets/icons/dicesLight.svg
    - assets/icons/dicesMid.svg
    - assets/icons/dollarBlue.svg
    - assets/icons/dollarBluedark.svg
    - assets/icons/dollarLight.svg
    - assets/icons/energyBlack.svg
    - assets/icons/energyLight.svg
    - assets/icons/energyMid.svg
    - assets/icons/face.svg
    - assets/icons/globe.svg
    - assets/icons/group.svg
    - assets/icons/lensDark.svg
    - assets/icons/lockDark.svg
    - assets/icons/lockLight.svg
    - assets/icons/lockMid.svg
    - assets/icons/mailDark.svg
    - assets/icons/moonDark.svg
    - assets/icons/moonLight.svg
    - assets/icons/piggyBlue.svg
    - assets/icons/piggyBluedark.svg
    - assets/icons/piggyLight.svg
    - assets/icons/questionCircleDark.svg
    - assets/icons/questionCirclePink.svg
    - assets/icons/questionDark.svg
    - assets/icons/questionPink.svg
    - assets/icons/rocketDark.svg
    - assets/icons/rocketMid.svg
    - assets/icons/rocketPink.svg
    - assets/icons/sackLight.svg
    - assets/icons/sackDark.svg
    - assets/icons/safeLight.svg
    - assets/icons/shieldDark.svg
    - assets/icons/shieldMid.svg
    - assets/icons/shieldPink.svg
    - assets/icons/soundDark.svg
    - assets/icons/soundPink.svg
    - assets/icons/3d/bag.png
    - assets/icons/3d/cashBtc.png
    - assets/icons/3d/handBtc.png
    - assets/icons/3d/Hourglass.png
    - assets/icons/3d/magnet.png
    - assets/icons/3d/roulette.png
    - assets/icons/3d/trophy.png
    - assets/logo.png
    - assets/redBear.png
    - assets/games/greatRhyno.png
    - assets/users/user1.png
    - assets/users/user2.png
    - assets/users/user3.png
    - assets/users/user4.png
    - assets/users/user5.png
    - assets/users/user6.png
    - assets/users/user8.png
    - assets/users/user9.png
    - assets/users/user10.png
    - assets/users/user11.png
    - assets/users/user12.png

